# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [17] # Minimum supported by Minecraft
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2.4.2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3.3.0
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifacts
          path: build/libs/
